name: flight_deals_console_app
services:
  backend:
    build: .
    volumes:
      - .:/app
      - ./Flight_Deals.xlsx:/app/Flight_Deals.xlsx
    env_file:
      - .env
    stdin_open: true
    tty: true
